mod pin;
mod registry;
mod render;
mod render_rules;

use std::env;
use std::ffi::OsStr;
use std::path::PathBuf;
use std::process::ExitCode;

#[derive(Debug, thiserror::Error)]
enum ControlError {
    #[error("{0}")]
    Usage(String),
    #[error("{0}")]
    Registry(String),
    #[error("{0}")]
    Renderer(String),
}

#[derive(Debug, PartialEq, Eq)]
struct RepairHint {
    purpose: &'static str,
    reason: &'static str,
    common_fixes: &'static [&'static str],
    docs_url: &'static str,
    repair_hint: &'static str,
}

impl ControlError {
    fn repair(&self) -> RepairHint {
        match self {
            Self::Usage(_) => RepairHint {
                purpose: "select one closed jeryu-tool control command",
                reason: "the command line is outside the accepted schema",
                common_fixes: &[
                    "pass --tool-root before the command",
                    "use --check for read-only validation",
                ],
                docs_url: "docs/testing.md",
                repair_hint: "rerun the thin ops entrypoint with only its documented flags",
            },
            Self::Registry(_) => RepairHint {
                purpose: "validate the canonical reusable-tool registry",
                reason: "registry or task input violated the closed schema",
                common_fixes: &[
                    "fix the named field",
                    "remove the duplicate id",
                    "correct the status or task reference",
                ],
                docs_url: "docs/tools-registry.md",
                repair_hint: "run ops/registry-summary.sh --check after correcting the named input",
            },
            Self::Renderer(_) => RepairHint {
                purpose: "render one governed Jankurai identity into claimed consumers",
                reason: "pin, custody, topology, or generated bytes did not match",
                common_fixes: &[
                    "use a clean canonical checkout",
                    "select its exact handed-off head",
                ],
                docs_url: "docs/testing.md",
                repair_hint: "run check mode first; never broaden or bypass the renderer custody checks",
            },
        }
    }
}

fn usage() -> &'static str {
    "usage: jeryu-toolctl --tool-root PATH <registry-summary|render-tool-manifest> [ARGS...]"
}

fn run() -> Result<i32, ControlError> {
    let mut args = env::args().skip(1);
    let Some(flag) = args.next() else {
        return Err(ControlError::Usage(usage().to_owned()));
    };
    if flag != "--tool-root" {
        return Err(ControlError::Usage(format!(
            "expected --tool-root before command\n{}",
            usage()
        )));
    }
    let root =
        PathBuf::from(args.next().ok_or_else(|| {
            ControlError::Usage(format!("--tool-root requires a path\n{}", usage()))
        })?);
    let command = args
        .next()
        .ok_or_else(|| ControlError::Usage(usage().to_owned()))?;
    let rest: Vec<String> = args.collect();
    match command.as_str() {
        "emit-ensure-script" => {
            render::emit_ensure_script(&root, &rest).map_err(ControlError::Renderer)
        }
        "registry-summary" => registry::run(&root, &rest).map_err(ControlError::Registry),
        "render-tool-manifest" => render::run(&root, &rest).map_err(ControlError::Renderer),
        _ => Err(ControlError::Usage(format!(
            "unknown command {command:?}\n{}",
            usage()
        ))),
    }
}

fn main() -> ExitCode {
    if env::var_os("JERYU_TOOL_GIT_ASKPASS").as_deref() == Some(OsStr::new("1")) {
        let args: Vec<String> = env::args().skip(1).collect();
        return match render::git_askpass(&args) {
            Ok(password) => {
                println!("{password}");
                ExitCode::SUCCESS
            }
            Err(_) => ExitCode::FAILURE,
        };
    }
    match run() {
        Ok(code) => ExitCode::from(u8::try_from(code).unwrap_or(1)),
        Err(message) => {
            eprintln!("{message}");
            let repair = message.repair();
            eprintln!(
                "purpose: {}\nreason: {}\ncommon_fixes: {}\ndocs_url: {}\nrepair_hint: {}",
                repair.purpose,
                repair.reason,
                repair.common_fixes.join("|"),
                repair.docs_url,
                repair.repair_hint
            );
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::ControlError;

    #[test]
    fn every_control_error_has_closed_agent_repair_guidance() {
        let errors = [
            ControlError::Usage("usage fixture".to_owned()),
            ControlError::Registry("registry fixture".to_owned()),
            ControlError::Renderer("renderer fixture".to_owned()),
        ];

        for error in errors {
            let repair = error.repair();
            assert!(!repair.purpose.is_empty());
            assert!(!repair.reason.is_empty());
            assert!(!repair.common_fixes.is_empty());
            assert!(repair.common_fixes.iter().all(|fix| !fix.is_empty()));
            assert!(repair.docs_url.starts_with("docs/"));
            assert!(repair.repair_hint.contains("run"));
        }
    }
}
