use regex::Regex;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub const PIN_MARKER_BEGIN: &str = "# BEGIN GENERATED JANKURAI PIN — DO NOT EDIT";
pub const PIN_MARKER_END: &str = "# END GENERATED JANKURAI PIN";
pub const WORKFLOW_PIN_MARKER_BEGIN: &str = "# BEGIN GENERATED JANKURAI WORKFLOW PIN — DO NOT EDIT";
pub const WORKFLOW_PIN_MARKER_END: &str = "# END GENERATED JANKURAI WORKFLOW PIN";

pub const PIN_ENV_FIELDS: [(&str, &str); 14] = [
    ("JANKURAI_REPO", "repo"),
    ("JANKURAI_TAG", "tag"),
    ("JANKURAI_REV", "rev"),
    ("JANKURAI_VERSION", "version"),
    ("JANKURAI_SEMVER", "semver"),
    ("JANKURAI_SOURCE_TREE", "source_tree"),
    ("JANKURAI_SOURCE_ARCHIVE_SHA256", "source_archive_sha256"),
    ("JANKURAI_CARGO_LOCK_SHA256", "cargo_lock_sha256"),
    ("JANKURAI_BINARY_SHA256", "binary_sha256"),
    ("JANKURAI_RUST_TOOLCHAIN", "rust_toolchain"),
    ("JANKURAI_RUSTC_VERSION", "rustc_version"),
    ("JANKURAI_CARGO_VERSION", "cargo_version"),
    ("JANKURAI_TARGET_TRIPLE", "target_triple"),
    ("JANKURAI_BUILD_MODE", "build_mode"),
];

#[derive(Debug, Clone)]
pub struct Pin(BTreeMap<String, String>);

impl Pin {
    pub fn load(tool_root: &Path) -> Result<Self, String> {
        let manifest = tool_root.join("tool-manifest.toml");
        let text = fs::read_to_string(&manifest)
            .map_err(|error| format!("failed to read {}: {error}", manifest.display()))?;
        let parsed: toml::Value = toml::from_str(&text)
            .map_err(|error| format!("failed to parse {}: {error}", manifest.display()))?;
        let table = parsed
            .get("jankurai")
            .and_then(toml::Value::as_table)
            .ok_or_else(|| "tool-manifest.toml missing [jankurai]".to_owned())?;
        let mut fields = BTreeMap::new();
        let mut missing = Vec::new();
        for (_, key) in PIN_ENV_FIELDS {
            match table.get(key).and_then(toml::Value::as_str) {
                Some(value) if !value.is_empty() => {
                    fields.insert(key.to_owned(), value.to_owned());
                }
                _ => missing.push(key),
            }
        }
        if !missing.is_empty() {
            return Err(format!(
                "tool-manifest.toml [jankurai] missing: {}",
                missing.join(", ")
            ));
        }
        let pin = Self(fields);
        if pin.get("repo") != "http://127.0.0.1:8787/git/jeryu/jankurai.git" {
            return Err(
                "Jankurai release source must be the approved local Jeryu forge URL".to_owned(),
            );
        }
        let sha = Regex::new("^[0-9a-f]{40}$").expect("constant regex");
        for key in ["rev", "source_tree"] {
            if !sha.is_match(pin.get(key)) {
                return Err(format!(
                    "invalid {key}: expected 40 lowercase hexadecimal characters"
                ));
            }
        }
        let digest = Regex::new("^[0-9a-f]{64}$").expect("constant regex");
        for key in [
            "source_archive_sha256",
            "cargo_lock_sha256",
            "binary_sha256",
        ] {
            if !digest.is_match(pin.get(key)) {
                return Err(format!("invalid {key}: expected SHA-256"));
            }
        }
        Ok(pin)
    }

    pub fn get(&self, key: &str) -> &str {
        self.0.get(key).map_or("", String::as_str)
    }

    pub fn env_text(&self) -> String {
        let mut lines = vec![
            "# GENERATED by ops/render-tool-manifest.sh from tool-manifest.toml — DO NOT EDIT."
                .to_owned(),
            "# This binds source, build environment, and installed binary identity.".to_owned(),
        ];
        lines.extend(
            PIN_ENV_FIELDS
                .iter()
                .map(|(env, key)| format!("{env}=\"{}\"", self.get(key))),
        );
        format!("{}\n", lines.join("\n"))
    }

    pub fn shell_block(&self) -> String {
        [
            PIN_MARKER_BEGIN.to_owned(),
            format!("export JERYU_JANKURAI_SOURCE_REPO=\"{}\"", self.get("repo")),
            format!("export JERYU_JANKURAI_VERSION=\"{}\"", self.get("version")),
            format!(
                "export JERYU_JANKURAI_SHA256=\"{}\"",
                self.get("binary_sha256")
            ),
            format!("export JERYU_JANKURAI_SOURCE_REV=\"{}\"", self.get("rev")),
            format!("export JERYU_JANKURAI_SOURCE_TAG=\"{}\"", self.get("tag")),
            format!(
                "export JERYU_JANKURAI_SOURCE_TREE=\"{}\"",
                self.get("source_tree")
            ),
            format!(
                "export JERYU_JANKURAI_SOURCE_ARCHIVE_SHA256=\"{}\"",
                self.get("source_archive_sha256")
            ),
            format!(
                "export JERYU_JANKURAI_CARGO_LOCK_SHA256=\"{}\"",
                self.get("cargo_lock_sha256")
            ),
            format!(
                "export JERYU_JANKURAI_RUST_TOOLCHAIN=\"{}\"",
                self.get("rust_toolchain")
            ),
            format!(
                "export JERYU_JANKURAI_RUSTC_VERSION=\"{}\"",
                self.get("rustc_version")
            ),
            format!(
                "export JERYU_JANKURAI_CARGO_VERSION=\"{}\"",
                self.get("cargo_version")
            ),
            format!(
                "export JERYU_JANKURAI_TARGET_TRIPLE=\"{}\"",
                self.get("target_triple")
            ),
            format!(
                "export JERYU_JANKURAI_BUILD_MODE=\"{}\"",
                self.get("build_mode")
            ),
            PIN_MARKER_END.to_owned(),
        ]
        .join("\n")
    }

    pub fn workflow_block(&self) -> String {
        let mut lines = vec![format!("  {WORKFLOW_PIN_MARKER_BEGIN}")];
        lines.extend(PIN_ENV_FIELDS.iter().map(|(name, key)| {
            format!(
                "  {name}: {}",
                serde_json::to_string(self.get(key)).expect("string JSON")
            )
        }));
        lines.push(format!("  {WORKFLOW_PIN_MARKER_END}"));
        lines.join("\n")
    }
}
