#!/usr/bin/env python3
"""Render every jankurai-pin consumer in the jeryu family from tool-manifest.toml.

tool-manifest.toml is the single source of truth. This script propagates the
`[jankurai]` pin into every consumer that would otherwise hardcode it:

  * generated/jankurai-pin.env              (canonical sourced env)
  * <repo>/ops/ci/ensure-jankurai.sh        (default JANKURAI_* assignments)
  * <repo>/ops/ci/lib.sh                     (require_jankurai expected version)
  * <repo>/ops/ci/common.sh                  (JERYU_JANKURAI_VERSION default)
  * <repo>/.github/workflows/*.yml           (JANKURAI_REPO/TAG/REV env)
  * <repo>/agent/ci-lanes.toml               (jankurai_version)
  * <repo>/agent/audit-policy.toml           (required_tool_version)
  * <repo>/images/agent-sandbox/Dockerfile   (ARG JANKURAI_REPO/REV/VERSION)

Modes:
  (default)  rewrite consumers in place, emit the pin env, print what changed.
  --check    rewrite into memory only; exit 1 if any consumer has drifted.

The rewrites are keyed by regex and are idempotent: running twice is a no-op.
A file that does not contain a given key is left untouched (not an error), so
this is safe to point at every repo in the family.
"""
from __future__ import annotations

import glob
import os
import re
import sys

try:
    import tomllib  # py3.11+
except ModuleNotFoundError:  # pragma: no cover - older hosts
    import tomli as tomllib  # type: ignore

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # jeryu-tool/
FAMILY_ROOT = os.path.dirname(REPO_ROOT)  # jeryu-split/
MANIFEST = os.path.join(REPO_ROOT, "tool-manifest.toml")


def load_pin() -> dict[str, str]:
    with open(MANIFEST, "rb") as fh:
        data = tomllib.load(fh)
    j = data["jankurai"]
    return {
        "repo": j["repo"],
        "tag": j["tag"],
        "rev": j["rev"],
        "version": j["version"],
        "semver": j["semver"],
    }


def pin_env_text(pin: dict[str, str]) -> str:
    return (
        "# GENERATED by ops/render-tool-manifest.sh from tool-manifest.toml — DO NOT EDIT.\n"
        "# Source this file to pin the jankurai toolchain; it is the family-wide truth.\n"
        f'JANKURAI_REPO="{pin["repo"]}"\n'
        f'JANKURAI_TAG="{pin["tag"]}"\n'
        f'JANKURAI_REV="{pin["rev"]}"\n'
        f'JANKURAI_VERSION="{pin["version"]}"\n'
        f'JANKURAI_SEMVER="{pin["semver"]}"\n'
    )


def rules_for(path: str, pin: dict[str, str]) -> list[tuple[str, str]]:
    """Return (regex, replacement) pairs that apply to `path`."""
    name = os.path.basename(path)
    rules: list[tuple[str, str]] = []

    if name == "ensure-jankurai.sh":
        rules += [
            (r'(JANKURAI_REPO="\$\{JANKURAI_REPO:-)[^}]*(\}")', pin["repo"]),
            (r'(JANKURAI_TAG="\$\{JANKURAI_TAG:-)[^}]*(\}")', pin["tag"]),
            (r'(JANKURAI_REV="\$\{JANKURAI_REV:-)[^}]*(\}")', pin["rev"]),
            (r'(JANKURAI_VERSION="\$\{JANKURAI_VERSION:-)[^}]*(\}")', pin["version"]),
        ]
    elif name == "lib.sh":
        rules += [(r'(local expected=")jankurai [^"]*(")', pin["version"])]
    elif name == "common.sh":
        rules += [(r'(JERYU_JANKURAI_VERSION="\$\{JANKURAI_VERSION:-)jankurai [^}]*(\}")', pin["version"])]
    elif name.endswith(".yml") and "workflows" in path:
        rules += [
            (r'(JANKURAI_REPO:\s*")[^"]*(")', pin["repo"]),
            (r'(JANKURAI_TAG:\s*")[^"]*(")', pin["tag"]),
            (r'(JANKURAI_REV:\s*")[^"]*(")', pin["rev"]),
        ]
    elif name == "ci-lanes.toml":
        rules += [(r'(jankurai_version\s*=\s*")jankurai [^"]*(")', pin["version"])]
    elif name == "audit-policy.toml":
        rules += [(r'(required_tool_version\s*=\s*")[^"]*(")', pin["semver"])]
    elif name == "Dockerfile" and "agent-sandbox" in path:
        rules += [
            (r'(ARG JANKURAI_REPO=)\S+', pin["repo"]),
            (r'(ARG JANKURAI_REV=)\S+', pin["rev"]),
            (r'(ARG JANKURAI_VERSION=")[^"]*(")', pin["version"]),
        ]
    return rules


def apply_rules(text: str, rules: list[tuple[str, str]]) -> str:
    for pattern, value in rules:
        # Two-group rules wrap the value; single-group (Dockerfile ARG bare) append it.
        if re.search(r"\(.*\).*\(.*\)", pattern):
            text = re.sub(pattern, lambda m, v=value: m.group(1) + v + m.group(2), text)
        else:
            text = re.sub(pattern, lambda m, v=value: m.group(1) + v, text)
    return text


def consumer_paths() -> list[str]:
    pats = [
        "*/ops/ci/ensure-jankurai.sh",
        "*/ops/ci/lib.sh",
        "*/ops/ci/common.sh",
        "*/.github/workflows/*.yml",
        "*/agent/ci-lanes.toml",
        "*/agent/audit-policy.toml",
        "*/images/agent-sandbox/Dockerfile",
    ]
    out: list[str] = []
    for pat in pats:
        out += glob.glob(os.path.join(FAMILY_ROOT, pat))
    return sorted(set(out))


def main() -> int:
    check = "--check" in sys.argv[1:]
    pin = load_pin()
    drifted: list[str] = []
    changed: list[str] = []

    # 1. canonical pin env
    env_path = os.path.join(REPO_ROOT, "generated", "jankurai-pin.env")
    env_text = pin_env_text(pin)
    os.makedirs(os.path.dirname(env_path), exist_ok=True)
    cur_env = open(env_path).read() if os.path.exists(env_path) else None
    if cur_env != env_text:
        (drifted if check else changed).append(env_path)
        if not check:
            open(env_path, "w").write(env_text)

    # 2. every consumer
    for path in consumer_paths():
        rules = rules_for(path, pin)
        if not rules:
            continue
        original = open(path).read()
        updated = apply_rules(original, rules)
        if updated != original:
            (drifted if check else changed).append(path)
            if not check:
                open(path, "w").write(updated)

    rel = lambda p: os.path.relpath(p, FAMILY_ROOT)
    if check:
        if drifted:
            print("jankurai pin DRIFT — these consumers differ from tool-manifest.toml:")
            for p in drifted:
                print(f"  - {rel(p)}")
            print("Run ops/render-tool-manifest.sh to resync.")
            return 1
        print(f"jankurai pin ok: all consumers match {pin['version']}")
        return 0

    if changed:
        print(f"rendered {pin['version']} into {len(changed)} file(s):")
        for p in changed:
            print(f"  - {rel(p)}")
    else:
        print(f"jankurai pin already current: {pin['version']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
