#!/usr/bin/env python3
"""Render the governed Jankurai identity into canonical Jeryu consumers.

The renderer deliberately walks an allow-list of canonical repositories. Scratch
worktrees and dated clones are never globbed into the release graph.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - older hosts
    import tomli as tomllib  # type: ignore


REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_REPOS = (
    "jeryu",
    "jeryu-cache",
    "jeryu-ci-runner",
    "jeryu-core",
    "jeryu-deploy",
    "jeryu-intelligence",
    "jeryu-jira",
    "jeryu-release-ops",
    "jeryu-tool",
    "jeryu-tool-finder",
    "jeryu-web",
)
MANIFEST = REPO_ROOT / "tool-manifest.toml"
PIN_MARKER_BEGIN = "# BEGIN GENERATED JANKURAI PIN — DO NOT EDIT"
PIN_MARKER_END = "# END GENERATED JANKURAI PIN"


def default_family_root() -> Path:
    override = os.environ.get("JERYU_FAMILY_ROOT")
    if override:
        return Path(override).resolve()
    parent = REPO_ROOT.parent
    return parent.parent if parent.name == ".worktrees" else parent


def load_pin() -> dict[str, str]:
    with MANIFEST.open("rb") as fh:
        data = tomllib.load(fh)
    j = data["jankurai"]
    required = (
        "repo",
        "tag",
        "rev",
        "version",
        "semver",
        "source_tree",
        "source_archive_sha256",
        "cargo_lock_sha256",
        "binary_sha256",
        "rust_toolchain",
        "rustc_version",
        "cargo_version",
        "target_triple",
        "build_mode",
    )
    missing = [key for key in required if not j.get(key)]
    if missing:
        raise SystemExit(f"tool-manifest.toml [jankurai] missing: {', '.join(missing)}")
    pin = {key: str(j[key]) for key in required}
    if pin["repo"] != "http://127.0.0.1:8787/git/jeryu/jankurai.git":
        raise SystemExit("Jankurai release source must be the approved local Jeryu forge URL")
    for key in ("rev", "source_tree"):
        if not re.fullmatch(r"[0-9a-f]{40}", pin[key]):
            raise SystemExit(f"invalid {key}: expected 40 lowercase hexadecimal characters")
    for key in ("source_archive_sha256", "cargo_lock_sha256", "binary_sha256"):
        if not re.fullmatch(r"[0-9a-f]{64}", pin[key]):
            raise SystemExit(f"invalid {key}: expected SHA-256")
    return pin


def pin_env_text(pin: dict[str, str]) -> str:
    names = (
        ("JANKURAI_REPO", "repo"),
        ("JANKURAI_TAG", "tag"),
        ("JANKURAI_REV", "rev"),
        ("JANKURAI_VERSION", "version"),
        ("JANKURAI_SEMVER", "semver"),
        ("JANKURAI_SOURCE_TREE", "source_tree"),
        ("JANKURAI_SOURCE_ARCHIVE_SHA256", "source_archive_sha256"),
        ("JANKURAI_CARGO_LOCK_SHA256", "cargo_lock_sha256"),
        ("JANKURAI_BINARY_SHA256", "binary_sha256"),
        ("JANKURAI_RUST_TOOLCHAIN", "rust_toolchain"),
        ("JANKURAI_RUSTC_VERSION", "rustc_version"),
        ("JANKURAI_CARGO_VERSION", "cargo_version"),
        ("JANKURAI_TARGET_TRIPLE", "target_triple"),
        ("JANKURAI_BUILD_MODE", "build_mode"),
    )
    lines = [
        "# GENERATED by ops/render-tool-manifest.sh from tool-manifest.toml — DO NOT EDIT.",
        "# This binds source, build environment, and installed binary identity.",
    ]
    lines.extend(f'{env}="{pin[key]}"' for env, key in names)
    return "\n".join(lines) + "\n"


def shell_pin_block(pin: dict[str, str]) -> str:
    return "\n".join(
        (
            PIN_MARKER_BEGIN,
            'export JERYU_GOVERNED_JANKURAI_BIN="${JERYU_JANKURAI_BIN:-/home/ubuntu/.jeryu/bin/jankurai}"',
            f'export JERYU_JANKURAI_VERSION="{pin["version"]}"',
            f'export JERYU_JANKURAI_SHA256="{pin["binary_sha256"]}"',
            f'export JERYU_JANKURAI_SOURCE_REV="{pin["rev"]}"',
            f'export JERYU_JANKURAI_SOURCE_TAG="{pin["tag"]}"',
            f'export JERYU_JANKURAI_SOURCE_TREE="{pin["source_tree"]}"',
            f'export JERYU_JANKURAI_SOURCE_ARCHIVE_SHA256="{pin["source_archive_sha256"]}"',
            f'export JERYU_JANKURAI_CARGO_LOCK_SHA256="{pin["cargo_lock_sha256"]}"',
            f'export JERYU_JANKURAI_RUST_TOOLCHAIN="{pin["rust_toolchain"]}"',
            f'export JERYU_JANKURAI_TARGET_TRIPLE="{pin["target_triple"]}"',
            PIN_MARKER_END,
        )
    )


def require_jankurai_function() -> str:
    return r'''require_jankurai() {
  local bin="${JERYU_GOVERNED_JANKURAI_BIN}"
  local bin_dir normalized resolved actual actual_sha
  if [[ "${bin}" != /* || ! -f "${bin}" || -L "${bin}" || ! -x "${bin}" ]]; then
    printf 'governed jankurai must be an absolute executable regular file: %s\n' "${bin}" >&2
    exit 1
  fi
  normalized="$(realpath -m "${bin}")"
  if [[ "${normalized}" != "${bin}" ]]; then
    printf 'governed jankurai path traverses a symlink: %s -> %s\n' "${bin}" "${normalized}" >&2
    exit 1
  fi
  bin_dir="$(dirname "${bin}")"
  export PATH="${bin_dir}:${PATH}"
  resolved="$(command -v jankurai 2>/dev/null || true)"
  if [[ "${resolved}" != "${bin}" ]]; then
    printf 'governed jankurai shadowed: expected %s, resolved %s\n' "${bin}" "${resolved:-missing}" >&2
    exit 1
  fi
  actual="$("${bin}" --version 2>/dev/null || true)"
  actual_sha="$(sha256sum "${bin}" 2>/dev/null | awk '{print $1}')"
  if [[ "${actual}" != "${JERYU_JANKURAI_VERSION}" ]] ||
     [[ "${actual_sha}" != "${JERYU_JANKURAI_SHA256}" ]]; then
    printf 'governed jankurai identity mismatch at %s: version=%s sha256=%s\n' \
      "${bin}" "${actual:-missing}" "${actual_sha:-missing}" >&2
    exit 1
  fi
  export JANKURAI_NO_UPDATE_CHECK=1 GIT_TERMINAL_PROMPT=0
}'''


def ensure_script_text(pin: dict[str, str]) -> str:
    return f'''#!/usr/bin/env bash
# GENERATED Jankurai verifier. Installation is owned only by jeryu-tool.
set -euo pipefail

{shell_pin_block(pin)}

{require_jankurai_function()}

require_jankurai
printf 'governed jankurai ok: %s sha256=%s at %s\\n' \\
  "${{JERYU_JANKURAI_VERSION}}" "${{JERYU_JANKURAI_SHA256}}" "${{JERYU_GOVERNED_JANKURAI_BIN}}"
'''


def replace_pin_block(text: str, pin: dict[str, str]) -> str:
    block = shell_pin_block(pin)
    marked = re.compile(
        rf"(?ms)\n*^{re.escape(PIN_MARKER_BEGIN)}$.*?^{re.escape(PIN_MARKER_END)}$\n*"
    )
    text = marked.sub("\n", text)
    match = re.search(r"(?m)^set -euo pipefail\s*$", text)
    if not match:
        return text
    return text[: match.end()] + "\n\n" + block + "\n\n" + text[match.end() :].lstrip()


def replace_require_function(text: str) -> str:
    pattern = re.compile(r"(?ms)^require_jankurai\(\) \{.*?^\}")
    return pattern.sub(lambda _: require_jankurai_function(), text)


def generic_identity_rules(text: str, pin: dict[str, str]) -> str:
    replacements = {
        "https://github.com/neverhuman/jankurai.git": pin["repo"],
        "68bd6114373cf407a930011b76669af306cb0cb1": pin["rev"],
        "v1.6.10-deadlang-precision": pin["tag"],
        "jankurai 1.6.10": pin["version"],
        "Jankurai 1.6.10": pin["version"].replace("jankurai", "Jankurai"),
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def render_consumer(path: Path, pin: dict[str, str]) -> str:
    text = path.read_text()
    rel = path.as_posix()
    if path.name == "ensure-jankurai.sh":
        return ensure_script_text(pin)
    if path.name == "lib.sh" and "/ops/ci/" in rel:
        return replace_require_function(replace_pin_block(text, pin))
    if path.suffix == ".sh":
        text = replace_pin_block(text, pin)
    if path.name in ("audit-policy.toml", "default-audit-policy.toml"):
        return re.sub(
            r'(required_tool_version\s*=\s*")[^"]*(")',
            rf'\g<1>{pin["semver"]}\g<2>',
            text,
        )
    if path.name == "ci-lanes.toml":
        return re.sub(
            r'(jankurai_version\s*=\s*")[^"]*(")',
            rf'\g<1>{pin["version"]}\g<2>',
            text,
        )
    if path.name == "native-cli-manifest.toml":
        block = re.compile(r'(?ms)(\[\[tools\]\]\s*id\s*=\s*"jankurai".*?)(?=\n\[\[tools\]\]|\Z)')

        def native_block(match: re.Match[str]) -> str:
            value = re.sub(
                r'(version\s*=\s*")[^"]*(")', rf'\g<1>{pin["semver"]}\g<2>', match.group(1)
            )
            value = re.sub(
                r'(observed_path\s*=\s*")[^"]*(")', r'\g<1>/home/ubuntu/.jeryu/bin/jankurai\g<2>', value
            )
            return re.sub(
                r'(observed_digest\s*=\s*")[^"]*(")', rf'\g<1>sha256:{pin["binary_sha256"]}\g<2>', value
            )

        text = block.sub(native_block, text)
    if path.name == "ci_bridge.rs":
        text = re.sub(
            r'(required_tool_version\s*=\s*\\?")[^"\\]*(\\?")',
            rf'\g<1>{pin["semver"]}\g<2>',
            text,
        )
    if path.name.endswith(".yml") and "/workflows/" in rel and "JANKURAI_REV:" in text:
        identity_lines = (
            ("JANKURAI_SOURCE_TREE", pin["source_tree"]),
            ("JANKURAI_SOURCE_ARCHIVE_SHA256", pin["source_archive_sha256"]),
            ("JANKURAI_CARGO_LOCK_SHA256", pin["cargo_lock_sha256"]),
            ("JANKURAI_BINARY_SHA256", pin["binary_sha256"]),
            ("JANKURAI_RUST_TOOLCHAIN", pin["rust_toolchain"]),
            ("JANKURAI_TARGET_TRIPLE", pin["target_triple"]),
        )
        for key, value in identity_lines:
            if re.search(rf"(?m)^\s*{key}:", text):
                text = re.sub(rf'(?m)^(\s*{key}:\s*)[^\n]*$', rf'\g<1>"{value}"', text)
                continue
            text = re.sub(
                r'(?m)^(\s*)JANKURAI_REV:(.*)$',
                lambda match, k=key, v=value: (
                    f"{match.group(1)}JANKURAI_REV:{match.group(2)}\n"
                    f'{match.group(1)}{k}: "{v}"'
                ),
                text,
                count=1,
            )
        text = re.sub(
            r'(?m)^      - name: Cache pinned auditor\n'
            r'        uses:.*\n'
            r'        with:\n'
            r'          path:.*\n'
            r'          key:.*\n',
            "",
            text,
        )
        text = re.sub(
            r'(?ms)^      - name: Install pinned jankurai\n'
            r'.*?(?=^      (?:#|- name:))',
            "      - name: Verify governed jankurai\n"
            "        run: |\n"
            "          source ops/ci/lib.sh\n"
            "          require_jankurai\n",
            text,
        )
    if path.name == "Dockerfile" and "agent-sandbox" in rel:
        docker_args = (
            ("JANKURAI_TAG", pin["tag"]),
            ("JANKURAI_SOURCE_TREE", pin["source_tree"]),
            ("JANKURAI_SOURCE_ARCHIVE_SHA256", pin["source_archive_sha256"]),
            ("JANKURAI_CARGO_LOCK_SHA256", pin["cargo_lock_sha256"]),
            ("JANKURAI_BINARY_SHA256", pin["binary_sha256"]),
            ("JANKURAI_RUST_TOOLCHAIN", pin["rust_toolchain"]),
            ("JANKURAI_TARGET_TRIPLE", pin["target_triple"]),
        )
        for key, value in docker_args:
            if re.search(rf"(?m)^ARG {key}=", text):
                text = re.sub(rf"(?m)^ARG {key}=.*$", f"ARG {key}={value}", text)
            else:
                text = re.sub(
                    r'(?m)^(ARG JANKURAI_VERSION=.*)$',
                    lambda match, k=key, v=value: f"{match.group(1)}\nARG {k}={v}",
                    text,
                    count=1,
                )
    if path.name == "README.md" and "agent-sandbox" in rel:
        text = text.replace("(**1.6.10**, rev-locked)", f"(**{pin['semver']}**, identity-locked)")
    if path.name == "smoke.sh" and "/agent-sandbox/" in rel:
        text = text.replace("pinned 1.6.10", f"pinned {pin['semver']}")
    if path.name == "pr-ci.sh":
        text = re.sub(
            r'(?ms)^# The pinned jankurai .*?^export PATH=.*?\n',
            "# Resolve and verify the absolute governed auditor before any lane runs.\n"
            "source ops/ci/lib.sh\n"
            "require_jankurai\n",
            text,
        )
        text = re.sub(r'(?m)^export PATH="\$\{CARGO_HOME:-\$HOME/\.cargo\}/bin:\$PATH"\n?', "", text)
        if "require_jankurai\n" not in text:
            text = text.replace(
                'cd "$repo_root"\n',
                'cd "$repo_root"\n\n'
                "# Resolve and verify the absolute governed auditor before any lane runs.\n"
                "source ops/ci/lib.sh\n"
                "require_jankurai\n",
                1,
            )
        if 'bash "$JERYU_TOOL_RENDER" --check\n' in text:
            text = text.replace(
                '  bash "$JERYU_TOOL_RENDER" --check\n',
                "  consumer_repo=\"$(awk -F'\\\"' '/^workspace =/ {print $2; exit}' agent/audit-policy.toml)\"\n"
                "  bash \"$JERYU_TOOL_RENDER\" --check --repo \"$consumer_repo\" \\\n"
                "    --repo-root \"$consumer_repo=$repo_root\"\n",
            )
        if "JERYU_TOOL_RENDER=" not in text:
            drift_block = (
                "# Verify only this PR worktree against the family manifest; the post-rollout\n"
                "# control-plane check verifies the complete canonical family.\n"
                'JERYU_TOOL_RENDER="${JERYU_TOOL_RENDER:-$repo_root/../jeryu-tool/ops/render-tool-manifest.sh}"\n'
                'if [ -x "$JERYU_TOOL_RENDER" ]; then\n'
                "  consumer_repo=\"$(awk -F'\\\"' '/^workspace =/ {print $2; exit}' agent/audit-policy.toml)\"\n"
                '  bash "$JERYU_TOOL_RENDER" --check --repo "$consumer_repo" \\\n'
                '    --repo-root "$consumer_repo=$repo_root"\n'
                "fi\n\n"
            )
            text = text.replace(
                'echo "[pr-ci] (jobs=$JOBS) standard lanes" >&2\n',
                drift_block + 'echo "[pr-ci] (jobs=$JOBS) standard lanes" >&2\n',
                1,
            )
    if path.name == "ci-doctor.sh" and "require_jankurai" not in text:
        marker = PIN_MARKER_END + "\n"
        text = text.replace(
            marker,
            marker + "\nsource \"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\" && pwd)/ops/ci/lib.sh\"\n"
            "require_jankurai\n",
            1,
        )
    return generic_identity_rules(text, pin)


def repo_root(family_root: Path, name: str, overrides: dict[str, Path]) -> Path:
    if name in overrides:
        return overrides[name]
    return REPO_ROOT if name == "jeryu-tool" else family_root / name


def consumer_paths(
    family_root: Path, repos: tuple[str, ...], overrides: dict[str, Path]
) -> list[Path]:
    patterns = (
        "ops/ci/ensure-jankurai.sh",
        "ops/ci/lib.sh",
        "ops/ci/common.sh",
        "ops/ci/coverage.sh",
        "ops/ci/pr-ci.sh",
        "ci-fast-push.sh",
        ".github/workflows/*.yml",
        "agent/ci-lanes.toml",
        "agent/audit-policy.toml",
        "agent/native-cli-manifest.toml",
        "images/agent-sandbox/Dockerfile",
        "images/agent-sandbox/README.md",
        "ops/agent-sandbox/smoke.sh",
        "scripts/ci-doctor.sh",
        "crates/jeryu-api/src/ci_bridge.rs",
        "crates/jeryu-repogate/tests/ci_lanes.rs",
        "docs/testing.md",
        "docs/audit-rules.md",
        "policy/default-audit-policy.toml",
    )
    paths: set[Path] = set()
    for name in repos:
        root = repo_root(family_root, name, overrides)
        if not root.is_dir():
            continue
        for pattern in patterns:
            paths.update(Path(match) for match in glob.glob(str(root / pattern)))
    return sorted(paths)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo", action="append", choices=CANONICAL_REPOS)
    parser.add_argument(
        "--repo-root",
        action="append",
        default=[],
        metavar="NAME=PATH",
        help="explicit clean worktree for one selected canonical repository",
    )
    parser.add_argument("--family-root", type=Path, default=default_family_root())
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    pin = load_pin()
    repos = tuple(args.repo) if args.repo else CANONICAL_REPOS
    overrides: dict[str, Path] = {}
    for value in args.repo_root:
        name, separator, raw_path = value.partition("=")
        if separator != "=" or name not in CANONICAL_REPOS or not raw_path:
            raise SystemExit(f"invalid --repo-root {value!r}; expected canonical-name=/absolute/path")
        path = Path(raw_path).resolve()
        if not path.is_dir() or not (path / ".git").exists():
            raise SystemExit(f"--repo-root is not a Git worktree: {path}")
        overrides[name] = path
    unexpected_overrides = set(overrides).difference(repos)
    if unexpected_overrides:
        raise SystemExit(f"--repo-root without matching --repo: {sorted(unexpected_overrides)}")
    changed: list[Path] = []

    env_path = REPO_ROOT / "generated" / "jankurai-pin.env"
    expected_env = pin_env_text(pin)
    current_env = env_path.read_text() if env_path.exists() else None
    if current_env != expected_env:
        changed.append(env_path)
        if not args.check:
            env_path.parent.mkdir(parents=True, exist_ok=True)
            env_path.write_text(expected_env)

    for path in consumer_paths(args.family_root.resolve(), repos, overrides):
        original = path.read_text()
        rendered = render_consumer(path, pin)
        if rendered != original:
            changed.append(path)
            if not args.check:
                path.write_text(rendered)

    def display(path: Path) -> str:
        try:
            return str(path.relative_to(args.family_root.resolve()))
        except ValueError:
            return str(path)

    if args.check and changed:
        print("jankurai identity DRIFT — render these canonical consumers:")
        for path in changed:
            print(f"  - {display(path)}")
        return 1
    if args.check:
        print(f"jankurai identity ok: {pin['version']} sha256={pin['binary_sha256']}")
        return 0
    if changed:
        print(f"rendered {pin['version']} into {len(changed)} file(s):")
        for path in changed:
            print(f"  - {display(path)}")
    else:
        print(f"jankurai identity already current: {pin['version']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
